### PR TITLE
Use PhpParser rather then preg to find includes

### LINKED ISSUE #157: Weird errors
Hello!

I'm trying to implement Bladestan into my work project, and I'm getting some weird syntax errors:

```json
    {
        "description": "Syntax error, unexpected ';', expecting ',' or ']' or ')'",
        "fingerprint": "33c91820b959eeadad57e2cbcede3c09e6ad46993b803e2e65590f98eb476f57",
        "severity": "blocker",
        "location": {
            "path": "app/Http/Controllers/AuthController.php",
            "lines": {
                "begin": 5
            }
        }
    },
```

the offending line is just an import that works just fine:

```php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Abstracts\BaseController; # this line
// ...
```

Both the file and the views look fine so I'm not sure why I'm getting these errors or how to debug.

Thanks!

### PR DESCRIPTION
**Pull request by calebdw**
Fixes #157

### CODE REVIEW

File: src/ValueObject/ViewDataCollector.php [hunk 1]
```diff
@@ -23,6 +23,17 @@ public function name(): string
         return $this->viewName;
     }
 
+    public function getName(): string
+    {
+        return $this->name();
+    }
+
+    public function getPath(): string
```
Comment (calebdw) [inline src/ValueObject/ViewDataCollector.php:31]: @AJenbo, I went ahead and added the `getPath` method---however, I think what we are actually passing to this class **is** the path and not the  view *name*. This could potentially cause listeners that need to do something with the view name to fail

Comment (AJenbo) [reply src/ValueObject/ViewDataCollector.php:31]: I think it initially was when I implemented but I ended up reverting some of the changes, thanks for pointing that out.

It does look like it gets the view name in 2/3 cases, I'll fix the other one as well.

Comment (AJenbo) [reply src/ValueObject/ViewDataCollector.php]: I split this part into it's own PR: https://github.com/bladestan/bladestan/pull/159
It's already merged since I set it to auto-merge and forgot that Bladestan doesn't require views since there was no one else to do so :sweat_smile: @calebdw if you could check the code and test if it still solves the issue (with Telescope) that would be much appreciated.

The  issue caught by the test will require porting some Regex to PhpParser, this is absolutly something we want to do in general and this isn't the hardest one to do so it's a good one to work one next, I'll try and do so later today.

Comment (calebdw) [reply src/ValueObject/ViewDataCollector.php]: @AJenbo, no worries! I was in church so couldn't check right away---but everything looks good and it works!

**Comment by AJenbo** [comment]
@calebdw again it turned out a bit awkward with the review process since you are the author of this PR but feel free to either open a follow up or write comments on this one and I'll make a new PR with the requested correction. Also it would be helpful if you can test out the changes :)

**Comment by calebdw** [comment]
@AJenbo, no worries! Thank you for fixing this so fast!

I just tested it out and it works great! But now Bladestan is just hanging at 75% complete so there's  likely other issues to be solved

**Comment by AJenbo** [comment]
It's a bit dumb but if PHPStan times out it assumes it died because of exceeding a memory limit so that message is almost useless. If you run `phpstan analyze --debug` you get to see each file it processes (and `dump()` output) so you can see where it gets stuck. I expect that it more likely is getting stuck in an infinite loop then having a memory leak.
